### ISSUE TITLE
performance against openmodelical compiler

### ISSUE THREAD

**Issue by alexbrownsoft** [marco-compiler/marco#18]
May i ask what is performance difference between marco and openmodelica compiler?

Does marco has some performance improvment compared to om compiiler?

**Comment by mscuttari** [comment]
Thanks for the question. This topic should indeed be treated somewhere in the docs.

MARCO is highly oriented towards large models (in the sense of number of equations).
At the moment this is achieved mainly by preserving array variables and for-equations. Variable-equation matching, sorting, and all the other algorithms inside the compiler are designed to exploit these compact declarations, and all the compilation pipeline avoids their unrolling as much as possible. The efficiency of the algorithms highly depends on the characteristics of the access functions (e.g., having linear accesses like `[i + 1]`, or constant ones like `[0]`). This results in different curves regarding compilation time, for which you can have a sense of by looking at the following papers and master thesis:

- [Array-Aware Matching: Taming the Complexity of Large-Scale Simulation Models](https://dl.acm.org/doi/10.1145/3611661)
- [MARCO: An Experimental High-Performance Compiler for Large-Scale Modelica Models](https://re.public.polimi.it/bitstream/11311/1260910/1/MARCO%20-%20An%20Experimental%20High-Performance%20Compiler%20for%20Large-Scale%20Modelica%20Models.pdf)
- [M.A.R.C.O. : an experimental high-performance Modelica compiler for large scale systems](https://www.politesi.polimi.it/handle/10589/170229)
- [Design and implementation of a Modelica compiler with MLIR and LLVM](https://www.politesi.polimi.it/handle/10589/179218)

Consider that the development is very active and results may have changed in the meanwhile, both in a good sense but also in a bad one, due to possible bugs.

There are also other optimizations, like the reduction of the system of equations given to the IDA solver, and the avoidance of garbage collection:
- [Clever DAE: Compiler Optimizations for Digital Twins at Scale](https://dl.acm.org/doi/abs/10.1145/3587135.3589945)
- [Efficient Memory Management for Modelica Simulations](https://doi.org/10.4230/OASIcs.PARMA-DITAM.2022.7)

Another key difference is the underlying technology used for compiler construction. MARCO is built on top of MLIR (and LLVM), while OMC has its own foundations. For this reason, the frontend of MARCO emits LLVM-IR code to be given to the backend of LLVM, whereas OMC generates C code.

Nonetheless, MARCO leverages OMC for instantiating the model of interest in the form of [Base Modelica](https://github.com/modelica/ModelicaSpecification/tree/MCP/0031/RationaleMCP/0031) code, which is a task that is not yet supported by the frontend of MARCO.

**Comment by mscuttari** [comment]
I'm closing the issue. Please re-open it if you have further questions.
